airline_app/booking/urls.py
from django.urls import path

from . import views
app_name = 'booking'
urlpatterns = [
    path('', views.index, name='index'),
    path('sign_up', views.sign_Up, name ='sign_Up'),
    path('userSettings/<str:userEmail>', views.userSettings, name='userSettings'),
    path('userSettings/<str:userEmail>/addAddress', views.addAddress, name='addAddress'),
    path('userSettings/<str:userEmail>/deleteAddress/<str:userAddress>', views.deleteAddress, name='deleteAddress'),
    path('userSettings/<str:userEmail>/addCreditCard', views.addCreditCard, name='addCreditCard'),
    path('userSettings/<str:userEmail>/deleteCreditCard/<str:userCreditCard>', views.deleteCreditCard, name='deleteCreditCard'),
    path('userSettings/<str:userEmail>/configureBilling', views.configureBilling, name='configureBilling'),
    path('userSettings/<str:userEmail>/configureBilling/deleteBilling/<str:billing_id>', views.deleteBilling, name='deleteBilling'),
    path('<str:userEmail>/store', views.store, name ='store'),
    path('<str:userEmail>/cart/<str:flight_number>', views.cart, name ='cart'),
    path('<str:userEmail>/flightsBought', views.flightsBought, name ='flightsBought'),
    path('<str:userEmail>/deleteFlight/<str:booking_id>', views.deleteFlight, name ='deleteFlight'),
]

airline_app/booking/templates/booking/bought.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'booking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'booking/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'booking/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'booking/bootstrap.min.js' %}"></script>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Airline Booking Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/booking/">Home </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">settings <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="user">
      <a href="#" data-toggle="modal" data-target="#modalLoginForm" style="text-decoration: none; color:white"><span
          id="userName">HELLO! {{ email }}<span></a>
    </div>
  </div>
</nav>

<div class = "container">
  
  <div class = "list_of_items">     
      {% block content %}
        <div>
          <h1>Tickets Purchased</h1>
          <a class="btn btn-primary" href="{% url 'booking:userSettings' email %}" name="Sign_In" value="Sign_In" style="font-size: small;">To Settings</a>
          <a class="btn btn-primary" href="/booking/{{ email }}/store">Buy Tickets</a>
          {% for flight in flight_objects %}
          
            <br>
            <hr>
            <div>
                <h3>From: {{flight.0.departure_airport.iata}}  ->  To: {{flight.0.destination_airport.iata}}</h3>
                <h5>Around ${{flight.0.price}}</h5>
                <h6>At: {{flight.0.departure_time}} | Arriving: {{flight.0.destination_time}}</h6>
                <p>{{flight.0.airline_name}}</p>
                <a href = "{% url 'booking:deleteFlight' email flight.1 %}" name="del" value="del" class="btn btn-danger">Delete</a>
            </div>
          {% endfor %}
        </div>
      {% endblock %}   
  </div>
</div>

airline_app/booking/templates/booking/cart.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'booking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'booking/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'booking/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'booking/bootstrap.min.js' %}"></script>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Airline Booking Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/booking/">Home </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">settings <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="user">
      <a href="#" data-toggle="modal" data-target="#modalLoginForm" style="text-decoration: none; color:white"><span
          id="userName">HELLO! {{ email }}<span></a>
    </div>
  </div>
</nav>
<div class = "container">
    <h1>Welcome to the Cart {{email}}!</h1>
    <a class="btn btn-primary" href="/booking/{{ email }}/store">Back to Store</a>
    <a class="btn btn-primary" href="/booking/{{ email }}/flightsBought">View Tickets Purchased</a>
  
    {% load crispy_forms_tags %}

        {% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
          <button type="submit" name="buy" value="buy" class="btn btn-success">BUY</button>
      </form>
       {% endblock %}
</div>

airline_app/booking/templates/booking/configureBilling.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'booking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'booking/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'booking/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'booking/bootstrap.min.js' %}"></script>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Airline Booking Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/booking/">Home </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">settings <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="user">
      <a href="#" data-toggle="modal" data-target="#modalLoginForm" style="text-decoration: none; color:white"><span
          id="userName">HELLO! {{ email }}<span></a>
    </div>
  </div>
</nav>

<div class = "container">
    <a class="btn btn-primary" href="{% url 'booking:userSettings' email %}" name="settings" value="settings" style="font-size: small;">To Settings</a>
    <div class = "list_of_items">
        {% load crispy_forms_tags %}
        {% block content %}
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" name="itemAdd" value="item" class="btn btn-primary">Add Billing Option</button>
          </form>
          <div>
            <h3>Billings Options</h3>
            {% for item in user_item_list %}
              <p>CreditCard: {{ item.0 }}- Address: {{item.1}}</p><a class = "btn btn-danger" href="/booking/userSettings/{{email}}/configureBilling/deleteBilling/{{item.2}}">Delete Payment Option</a>
            {% endfor %}
          </div>
        {% endblock %}   
    </div>
    
  </div>

airline_app/booking/templates/booking/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'booking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'booking/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'booking/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'booking/bootstrap.min.js' %}"></script>


<!---------------------------------------------------------------   NAVBAR     ----------------------------------------------------------------->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Airline Booking Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/booking/bookings">Bookings</a>
      </li>
    </ul>
    <div class="user">
      <a href="#" data-toggle="modal" data-target="#modalLoginForm" style="text-decoration: none; color:white"><span
          id="userName">Please Sign in<span></a>
    </div>
  </div>
</nav>


<!-----------------------------------------------------------------  MODAL  ----------------------------------------------------------------->

<div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Sign in</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <!--THERE IS GOING TO BE A FORM THAT POINTS TO SIGN IN-->
        {% load crispy_forms_tags %}

        {% block content %}
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <div class="modal-footer d-flex justify-content-center">
            <button type="submit" name="Sign_In" value="login" class="btn btn-primary">Sign in</button>
            <a href="{% url 'booking:sign_Up' %}" name="Sign_Up" value="Subscribe" style="font-size: small;">Sign Up</a>
          </div>
        </form>
        {% endblock %}
      </div>

    </div>
  </div>
</div>


<script>
  $(document).ready(function () {

    $("#modalLoginForm").modal('show');

  });
</script>

airline_app/booking/templates/booking/modifyItem.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'booking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'booking/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'booking/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'booking/bootstrap.min.js' %}"></script>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Airline Booking Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/booking/">Home </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">settings <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="user">
      <a href="#" data-toggle="modal" data-target="#modalLoginForm" style="text-decoration: none; color:white"><span
          id="userName">HELLO! {{ email }}<span></a>
    </div>
  </div>
</nav>

<div class = "container">
  <a class="btn btn-primary" href="{% url 'booking:userSettings' email %}" name="Sign_In" value="Sign_In" style="font-size: small;">To Settings</a>
  <div class = "list_of_items">
      {% load crispy_forms_tags %}
      {% block content %}
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" name="itemAdd" value="item" class="btn btn-primary">Add {{item_changing}}</button>
        </form>
        <div>
          <h1>{{item_changing}}</h1>
          {% for item in user_item_list %}
          <p>{{ item.0 }}<p><a class = "btn btn-danger" href="/booking/userSettings/{{email}}/delete{{item_changing}}/{{item.1}}">Delete {{item_changing}}</a>
          {% endfor %}
        </div>
      {% endblock %}   
  </div>
</div>




airline_app/booking/templates/booking/sign_up.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'booking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'booking/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'booking/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'booking/bootstrap.min.js' %}"></script>


<!---------------------------------------------------------------   NAVBAR     ----------------------------------------------------------------->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Airline Booking Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/booking/bookings">Bookings</a>
      </li>
    </ul>
    <div class="user">
      <a href="#" data-toggle="modal" data-target="#modalLoginForm" style="text-decoration: none; color:white"><span
          id="userName">Please Sign in<span></a>
    </div>
  </div>
</nav>


<!-----------------------------------------------------------------  MODAL  ----------------------------------------------------------------->

<div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Sign Up</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <!--THERE IS GOING TO BE A FORM THAT POINTS TO SIGN IN-->
        {% load crispy_forms_tags %}

        {% block content %}
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <div class="modal-footer d-flex justify-content-center">
            <button type="submit" name="sign_Up" value="sign_Up" class="btn btn-primary">Sign Up</button>
            <a href="{% url 'booking:index' %}" name="Sign_In" value="Sign_In" style="font-size: small;">Sign In</a>
          </div>
        </form>
        {% endblock %}
      </div>

    </div>
  </div>
</div>


<script>
  $(document).ready(function () {

    $("#modalLoginForm").modal('show');

  });
</script>


airline_app/booking/templates/booking/store.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'booking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'booking/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'booking/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'booking/bootstrap.min.js' %}"></script>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Airline Booking Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/booking/">Home </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">settings <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="user">
      <a href="#" data-toggle="modal" data-target="#modalLoginForm" style="text-decoration: none; color:white"><span
          id="userName">HELLO! {{ email }}<span></a>
    </div>
  </div>
</nav>
<div class = "container">
    <h1>Welcome to the Store {{email}}!</h1>
    <a class="btn btn-primary" href="{% url 'booking:userSettings' email %}" name="Sign_In" value="Sign_In" style="font-size: small;">To Settings</a>
    <a class="btn btn-primary" href="/booking/{{ email }}/flightsBought">View Tickets Purchased</a>
    {% block content %}
        {% for flight in list_of_flights %}
        <br>
        <hr>    
        <div>
            <h3>From: {{flight.departure_airport.iata}}  ->  To: {{flight.destination_airport.iata}}</h3>
            <h5>Around ${{flight.price}}</h5>
            <h6>At: {{flight.departure_time}} | Arriving: {{flight.destination_time}}</h6>
            <p>{{flight.airline_name}}</p>
            <a href = "{% url 'booking:cart' email flight.flight_number %}" name="buy" value="buy" class="btn btn-success">BUY</a>
        </div>
        <br>
        {% endfor %}
      {% endblock %} 
</div>

airline_app/booking/templates/booking/userBilling.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'booking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'booking/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'booking/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'booking/bootstrap.min.js' %}"></script>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Airline Booking Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/booking/">Home </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">settings <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="user">
      <a href="#" data-toggle="modal" data-target="#modalLoginForm" style="text-decoration: none; color:white"><span
          id="userName">HELLO! {{ email }}<span></a>
    </div>
  </div>
</nav>

<div class = "container">
    <a href="{% url 'booking:userSettings' email %}" name="settings" value="settings" style="font-size: small;">To Settings</a>
    <div class = "list_of_items">
        {% load crispy_forms_tags %}
        {% block content %}
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" name="itemAdd" value="item" class="btn btn-primary">Add Billing Option</button>
          </form>
        {% endblock %}   
    </div>
  </div>

airline_app/booking/templates/booking/userSettings.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'booking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'booking/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'booking/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'booking/bootstrap.min.js' %}"></script>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Airline Booking Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/booking/">Home </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">settings <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="user">
      <a href="#" data-toggle="modal" data-target="#modalLoginForm" style="text-decoration: none; color:white"><span
          id="userName">HELLO! {{ email }}<span></a>
    </div>
  </div>
</nav>
<div class = "container">
<a class="btn btn-primary" href="/booking/userSettings/{{ email }}/addAddress">Add/Delete Address</a>
<a class="btn btn-primary" href="/booking/userSettings/{{ email }}/addCreditCards">Add/Delete Credit Cards</a>
<a class="btn btn-primary" href="/booking/userSettings/{{ email }}/configureBilling">Configure Billiing Payment</a>
</div>













